### ISSUE TITLE
GHA fails after #7 is merged

### ISSUE THREAD

**Issue by kbjarkefur** [lsms-worldbank/adodownr#14]
After #7 is merged, I get the error below in this [GHA-job](https://github.com/lsms-worldbank/labeller/actions/runs/7657047890/job/20866802424) in for repo [labeller](https://github.com/lsms-worldbank/labeller)

```
Error: Error: [ENOENT] Failed to copy '/home/runner/work/labeller/labeller/README.md' to '/home/runner/work/labeller/labeller/index.qmd': no such file or directory
```

Does this error message make sense to you @arthur-shaw ? I wonder if the duplicated `labeller/labeller` can be the error?

**Comment by arthur-shaw** [comment]
I suspect this is an issue that results from combining the GitHub Pages Deploy Action and the (default) deletion of the site in adodownr. From some quick research, it looks like the GHA (sensibly) deletes all old files before commiting new ones. Meanwhile, adodownr deletes files before creating a new site. There might be racing conditions going on here. 

I'll tinker with this on my test_gha repo. I think if I change the adodownr default value for `rm_old_sidte_dir` to `FALSE` (see [here](https://github.com/lsms-worldbank/adodownr/blob/e63c830887b23b1fbadf2bce883f2f8dd1683ae8/R/build.R#L189)), all will be good again.

Sorry, being a GHA newb, I'm testing in production 🤣

**Comment by arthur-shaw** [comment]
Through experimentation with test_gha repo, I learned that the site should not be deleted be the GHA deploy step (even though I don't quite understand why). (See [this run ](https://github.com/arthur-shaw/test_gha/actions/runs/7712889622)and [this run](https://github.com/arthur-shaw/test_gha/actions/runs/7713598873).)

Hence, I made a few changes to adodownr:

- Revised how package handles deleting--and, importantly--not deleting the site in 9a96d986df833d4e72db560df221745ace10c5b9
- Ovewrite the site index file in d91ef3c9fba2f18e5de5e602b43f3d23d387aeed , since all other files are ovewritten (through a different mechanism) as the site is built.
- Fix an uncaught error in the logic of extracting metadata in 686f9da78236e527e2afe1d2229faca4c7c18a93. While no error appeared on local deployment, it arose on GHA deployment.
- By default, do not delete the site in 8eef7211916ed0e3055ad7446d6a6a78730ed3f3. For local deployments, where one needs/wants the site to be deleted, set `rm_old_site_dir = TRUE`.
